### ISSUE TITLE
Incorrect logo

### ISSUE THREAD

**Issue by ghost** [memetic-institute/Money-printer-go-BRRR#2]
The Federal Reserve Bank does NOT print United States Dollars. The United States Government does via the U.S. Bureau of Engraving and Printing.

The Federal Reserve Bank is not a government agency, so it doesn't create US currency.

**Comment by Burry** [comment]
It’s a visual metaphor. Who cares where physical dollars and coins are manufactured?

>The Bureau of Engraving and Printing (BEP) is a government agency within the United States Department of the Treasury that designs and produces a variety of security products for the United States government, most notable of which is Federal Reserve Notes (paper money) for the Federal Reserve, the nation's central bank...

https://en.m.wikipedia.org/wiki/Bureau_of_Engraving_and_Printing

**Comment by NPC64927130** [comment]
The BEP mints currency that the Fed issues. The money printer is a visual metaphor. Who cares who manufactures the physical bills when the _vast_ majority of USD is digital.
