### ISSUE TITLE
Support Fed Balance Sheet Charting

### ISSUE THREAD

**Issue by brandongalbraith** [memetic-institute/Money-printer-go-BRRR#4]
Aloha! Would you accept a pull request to include the [Fed's balance sheet](https://fred.stlouisfed.org/series/WALCL) alongside the existing charts?

**Comment by NPC64927130** [comment]
Sorry for being absent, will take a look at this

**Comment by brandongalbraith** [comment]
No worries, big fan, thanks for taking the time to consider.
